//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ShowUI.ISCB05_Service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="B05_ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class B05_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback checkRickSoftwareOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkwannacryOperationCompleted;
        
        private System.Threading.SendOrPostCallback B05_SI_YR_RTRATE_SEARCHOperationCompleted;
        
        private System.Threading.SendOrPostCallback P_B05_SI_YR_RTRATE_CONTROLOperationCompleted;
        
        private System.Threading.SendOrPostCallback SHOWUI_UNLOCK_RECORDOperationCompleted;
        
        private System.Threading.SendOrPostCallback B05_SI_GETFAKE_YROperationCompleted;
        
        private System.Threading.SendOrPostCallback B05_SI_ARLO_CARD_SEARCHOperationCompleted;
        
        private System.Threading.SendOrPostCallback B05_SI_ARLO_INSERT_CARDOperationCompleted;
        
        private System.Threading.SendOrPostCallback B05_SI_ARLO_UPDATE_CARDOperationCompleted;
        
        private System.Threading.SendOrPostCallback P_B05_ARLO_UPH_SOLVEDOperationCompleted;
        
        private System.Threading.SendOrPostCallback P_B05_ARLO_UPH_CONTROLOperationCompleted;
        
        private System.Threading.SendOrPostCallback P_B05_QA_LCR_SEARCHOperationCompleted;
        
        private System.Threading.SendOrPostCallback P_B05_QA_LCR_DATAOperationCompleted;
        
        private System.Threading.SendOrPostCallback P_B05_TE_CHECK_USERSOperationCompleted;
        
        private System.Threading.SendOrPostCallback P_B05_MEASURE_LUX_CONTROLOperationCompleted;
        
        private System.Threading.SendOrPostCallback P_B05_MEASURE_LUX_DTOperationCompleted;
        
        private System.Threading.SendOrPostCallback P_B05_MEASURE_LUX_DTNEWOperationCompleted;
        
        private System.Threading.SendOrPostCallback P_B05_ITEMNAME_CONFIGOperationCompleted;
        
        private System.Threading.SendOrPostCallback P_B05_CHECK_GOLDEN_DATAOperationCompleted;
        
        private System.Threading.SendOrPostCallback P_B05_ERROR_TRACKINGOperationCompleted;
        
        private System.Threading.SendOrPostCallback P_B05_CALIBRATION_CONTROLOperationCompleted;
        
        private System.Threading.SendOrPostCallback P_B05_MYDAS_SEARCHOperationCompleted;
        
        private System.Threading.SendOrPostCallback SHOWUI_SPECIAL_LOCKOperationCompleted;
        
        private System.Threading.SendOrPostCallback SHOWUI_LOCK_VALIDATIONOperationCompleted;
        
        private System.Threading.SendOrPostCallback AUTO_NOTICEOperationCompleted;
        
        private System.Threading.SendOrPostCallback SHOWUI_BACKEND_INFOOperationCompleted;
        
        private System.Threading.SendOrPostCallback P_B05_SMTTOP10ERRORCODEOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public B05_Service() {
            this.Url = global::ShowUI.Properties.Settings.Default.ShowUI_ISCB05_Service_B05_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event checkRickSoftwareCompletedEventHandler checkRickSoftwareCompleted;
        
        /// <remarks/>
        public event checkwannacryCompletedEventHandler checkwannacryCompleted;
        
        /// <remarks/>
        public event B05_SI_YR_RTRATE_SEARCHCompletedEventHandler B05_SI_YR_RTRATE_SEARCHCompleted;
        
        /// <remarks/>
        public event P_B05_SI_YR_RTRATE_CONTROLCompletedEventHandler P_B05_SI_YR_RTRATE_CONTROLCompleted;
        
        /// <remarks/>
        public event SHOWUI_UNLOCK_RECORDCompletedEventHandler SHOWUI_UNLOCK_RECORDCompleted;
        
        /// <remarks/>
        public event B05_SI_GETFAKE_YRCompletedEventHandler B05_SI_GETFAKE_YRCompleted;
        
        /// <remarks/>
        public event B05_SI_ARLO_CARD_SEARCHCompletedEventHandler B05_SI_ARLO_CARD_SEARCHCompleted;
        
        /// <remarks/>
        public event B05_SI_ARLO_INSERT_CARDCompletedEventHandler B05_SI_ARLO_INSERT_CARDCompleted;
        
        /// <remarks/>
        public event B05_SI_ARLO_UPDATE_CARDCompletedEventHandler B05_SI_ARLO_UPDATE_CARDCompleted;
        
        /// <remarks/>
        public event P_B05_ARLO_UPH_SOLVEDCompletedEventHandler P_B05_ARLO_UPH_SOLVEDCompleted;
        
        /// <remarks/>
        public event P_B05_ARLO_UPH_CONTROLCompletedEventHandler P_B05_ARLO_UPH_CONTROLCompleted;
        
        /// <remarks/>
        public event P_B05_QA_LCR_SEARCHCompletedEventHandler P_B05_QA_LCR_SEARCHCompleted;
        
        /// <remarks/>
        public event P_B05_QA_LCR_DATACompletedEventHandler P_B05_QA_LCR_DATACompleted;
        
        /// <remarks/>
        public event P_B05_TE_CHECK_USERSCompletedEventHandler P_B05_TE_CHECK_USERSCompleted;
        
        /// <remarks/>
        public event P_B05_MEASURE_LUX_CONTROLCompletedEventHandler P_B05_MEASURE_LUX_CONTROLCompleted;
        
        /// <remarks/>
        public event P_B05_MEASURE_LUX_DTCompletedEventHandler P_B05_MEASURE_LUX_DTCompleted;
        
        /// <remarks/>
        public event P_B05_MEASURE_LUX_DTNEWCompletedEventHandler P_B05_MEASURE_LUX_DTNEWCompleted;
        
        /// <remarks/>
        public event P_B05_ITEMNAME_CONFIGCompletedEventHandler P_B05_ITEMNAME_CONFIGCompleted;
        
        /// <remarks/>
        public event P_B05_CHECK_GOLDEN_DATACompletedEventHandler P_B05_CHECK_GOLDEN_DATACompleted;
        
        /// <remarks/>
        public event P_B05_ERROR_TRACKINGCompletedEventHandler P_B05_ERROR_TRACKINGCompleted;
        
        /// <remarks/>
        public event P_B05_CALIBRATION_CONTROLCompletedEventHandler P_B05_CALIBRATION_CONTROLCompleted;
        
        /// <remarks/>
        public event P_B05_MYDAS_SEARCHCompletedEventHandler P_B05_MYDAS_SEARCHCompleted;
        
        /// <remarks/>
        public event SHOWUI_SPECIAL_LOCKCompletedEventHandler SHOWUI_SPECIAL_LOCKCompleted;
        
        /// <remarks/>
        public event SHOWUI_LOCK_VALIDATIONCompletedEventHandler SHOWUI_LOCK_VALIDATIONCompleted;
        
        /// <remarks/>
        public event AUTO_NOTICECompletedEventHandler AUTO_NOTICECompleted;
        
        /// <remarks/>
        public event SHOWUI_BACKEND_INFOCompletedEventHandler SHOWUI_BACKEND_INFOCompleted;
        
        /// <remarks/>
        public event P_B05_SMTTOP10ERRORCODECompletedEventHandler P_B05_SMTTOP10ERRORCODECompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checkRickSoftware", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string checkRickSoftware(string pc_name) {
            object[] results = this.Invoke("checkRickSoftware", new object[] {
                        pc_name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void checkRickSoftwareAsync(string pc_name) {
            this.checkRickSoftwareAsync(pc_name, null);
        }
        
        /// <remarks/>
        public void checkRickSoftwareAsync(string pc_name, object userState) {
            if ((this.checkRickSoftwareOperationCompleted == null)) {
                this.checkRickSoftwareOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckRickSoftwareOperationCompleted);
            }
            this.InvokeAsync("checkRickSoftware", new object[] {
                        pc_name}, this.checkRickSoftwareOperationCompleted, userState);
        }
        
        private void OncheckRickSoftwareOperationCompleted(object arg) {
            if ((this.checkRickSoftwareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkRickSoftwareCompleted(this, new checkRickSoftwareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checkwannacry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool checkwannacry(string myIP) {
            object[] results = this.Invoke("checkwannacry", new object[] {
                        myIP});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void checkwannacryAsync(string myIP) {
            this.checkwannacryAsync(myIP, null);
        }
        
        /// <remarks/>
        public void checkwannacryAsync(string myIP, object userState) {
            if ((this.checkwannacryOperationCompleted == null)) {
                this.checkwannacryOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckwannacryOperationCompleted);
            }
            this.InvokeAsync("checkwannacry", new object[] {
                        myIP}, this.checkwannacryOperationCompleted, userState);
        }
        
        private void OncheckwannacryOperationCompleted(object arg) {
            if ((this.checkwannacryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkwannacryCompleted(this, new checkwannacryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/B05_SI_YR_RTRATE_SEARCH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet B05_SI_YR_RTRATE_SEARCH() {
            object[] results = this.Invoke("B05_SI_YR_RTRATE_SEARCH", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void B05_SI_YR_RTRATE_SEARCHAsync() {
            this.B05_SI_YR_RTRATE_SEARCHAsync(null);
        }
        
        /// <remarks/>
        public void B05_SI_YR_RTRATE_SEARCHAsync(object userState) {
            if ((this.B05_SI_YR_RTRATE_SEARCHOperationCompleted == null)) {
                this.B05_SI_YR_RTRATE_SEARCHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnB05_SI_YR_RTRATE_SEARCHOperationCompleted);
            }
            this.InvokeAsync("B05_SI_YR_RTRATE_SEARCH", new object[0], this.B05_SI_YR_RTRATE_SEARCHOperationCompleted, userState);
        }
        
        private void OnB05_SI_YR_RTRATE_SEARCHOperationCompleted(object arg) {
            if ((this.B05_SI_YR_RTRATE_SEARCHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.B05_SI_YR_RTRATE_SEARCHCompleted(this, new B05_SI_YR_RTRATE_SEARCHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/P_B05_SI_YR_RTRATE_CONTROL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string P_B05_SI_YR_RTRATE_CONTROL(System.Data.DataTable dt) {
            object[] results = this.Invoke("P_B05_SI_YR_RTRATE_CONTROL", new object[] {
                        dt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void P_B05_SI_YR_RTRATE_CONTROLAsync(System.Data.DataTable dt) {
            this.P_B05_SI_YR_RTRATE_CONTROLAsync(dt, null);
        }
        
        /// <remarks/>
        public void P_B05_SI_YR_RTRATE_CONTROLAsync(System.Data.DataTable dt, object userState) {
            if ((this.P_B05_SI_YR_RTRATE_CONTROLOperationCompleted == null)) {
                this.P_B05_SI_YR_RTRATE_CONTROLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnP_B05_SI_YR_RTRATE_CONTROLOperationCompleted);
            }
            this.InvokeAsync("P_B05_SI_YR_RTRATE_CONTROL", new object[] {
                        dt}, this.P_B05_SI_YR_RTRATE_CONTROLOperationCompleted, userState);
        }
        
        private void OnP_B05_SI_YR_RTRATE_CONTROLOperationCompleted(object arg) {
            if ((this.P_B05_SI_YR_RTRATE_CONTROLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.P_B05_SI_YR_RTRATE_CONTROLCompleted(this, new P_B05_SI_YR_RTRATE_CONTROLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SHOWUI_UNLOCK_RECORD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SHOWUI_UNLOCK_RECORD(string ate_ip, string ate_name, string iLine, string iModel, string iStation, string iErrorCode, string iUnlockEmp, string iConfirmEmp, string iLockTime, string iAction) {
            object[] results = this.Invoke("SHOWUI_UNLOCK_RECORD", new object[] {
                        ate_ip,
                        ate_name,
                        iLine,
                        iModel,
                        iStation,
                        iErrorCode,
                        iUnlockEmp,
                        iConfirmEmp,
                        iLockTime,
                        iAction});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SHOWUI_UNLOCK_RECORDAsync(string ate_ip, string ate_name, string iLine, string iModel, string iStation, string iErrorCode, string iUnlockEmp, string iConfirmEmp, string iLockTime, string iAction) {
            this.SHOWUI_UNLOCK_RECORDAsync(ate_ip, ate_name, iLine, iModel, iStation, iErrorCode, iUnlockEmp, iConfirmEmp, iLockTime, iAction, null);
        }
        
        /// <remarks/>
        public void SHOWUI_UNLOCK_RECORDAsync(string ate_ip, string ate_name, string iLine, string iModel, string iStation, string iErrorCode, string iUnlockEmp, string iConfirmEmp, string iLockTime, string iAction, object userState) {
            if ((this.SHOWUI_UNLOCK_RECORDOperationCompleted == null)) {
                this.SHOWUI_UNLOCK_RECORDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSHOWUI_UNLOCK_RECORDOperationCompleted);
            }
            this.InvokeAsync("SHOWUI_UNLOCK_RECORD", new object[] {
                        ate_ip,
                        ate_name,
                        iLine,
                        iModel,
                        iStation,
                        iErrorCode,
                        iUnlockEmp,
                        iConfirmEmp,
                        iLockTime,
                        iAction}, this.SHOWUI_UNLOCK_RECORDOperationCompleted, userState);
        }
        
        private void OnSHOWUI_UNLOCK_RECORDOperationCompleted(object arg) {
            if ((this.SHOWUI_UNLOCK_RECORDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SHOWUI_UNLOCK_RECORDCompleted(this, new SHOWUI_UNLOCK_RECORDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/B05_SI_GETFAKE_YR", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string B05_SI_GETFAKE_YR(string ate_ip, string ate_name, string iModel, string iStation, string realYR, string realRTR, ref double FAKE_YR, ref double FAKE_TRR) {
            object[] results = this.Invoke("B05_SI_GETFAKE_YR", new object[] {
                        ate_ip,
                        ate_name,
                        iModel,
                        iStation,
                        realYR,
                        realRTR,
                        FAKE_YR,
                        FAKE_TRR});
            FAKE_YR = ((double)(results[1]));
            FAKE_TRR = ((double)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void B05_SI_GETFAKE_YRAsync(string ate_ip, string ate_name, string iModel, string iStation, string realYR, string realRTR, double FAKE_YR, double FAKE_TRR) {
            this.B05_SI_GETFAKE_YRAsync(ate_ip, ate_name, iModel, iStation, realYR, realRTR, FAKE_YR, FAKE_TRR, null);
        }
        
        /// <remarks/>
        public void B05_SI_GETFAKE_YRAsync(string ate_ip, string ate_name, string iModel, string iStation, string realYR, string realRTR, double FAKE_YR, double FAKE_TRR, object userState) {
            if ((this.B05_SI_GETFAKE_YROperationCompleted == null)) {
                this.B05_SI_GETFAKE_YROperationCompleted = new System.Threading.SendOrPostCallback(this.OnB05_SI_GETFAKE_YROperationCompleted);
            }
            this.InvokeAsync("B05_SI_GETFAKE_YR", new object[] {
                        ate_ip,
                        ate_name,
                        iModel,
                        iStation,
                        realYR,
                        realRTR,
                        FAKE_YR,
                        FAKE_TRR}, this.B05_SI_GETFAKE_YROperationCompleted, userState);
        }
        
        private void OnB05_SI_GETFAKE_YROperationCompleted(object arg) {
            if ((this.B05_SI_GETFAKE_YRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.B05_SI_GETFAKE_YRCompleted(this, new B05_SI_GETFAKE_YRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/B05_SI_ARLO_CARD_SEARCH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet B05_SI_ARLO_CARD_SEARCH(string iCardID) {
            object[] results = this.Invoke("B05_SI_ARLO_CARD_SEARCH", new object[] {
                        iCardID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void B05_SI_ARLO_CARD_SEARCHAsync(string iCardID) {
            this.B05_SI_ARLO_CARD_SEARCHAsync(iCardID, null);
        }
        
        /// <remarks/>
        public void B05_SI_ARLO_CARD_SEARCHAsync(string iCardID, object userState) {
            if ((this.B05_SI_ARLO_CARD_SEARCHOperationCompleted == null)) {
                this.B05_SI_ARLO_CARD_SEARCHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnB05_SI_ARLO_CARD_SEARCHOperationCompleted);
            }
            this.InvokeAsync("B05_SI_ARLO_CARD_SEARCH", new object[] {
                        iCardID}, this.B05_SI_ARLO_CARD_SEARCHOperationCompleted, userState);
        }
        
        private void OnB05_SI_ARLO_CARD_SEARCHOperationCompleted(object arg) {
            if ((this.B05_SI_ARLO_CARD_SEARCHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.B05_SI_ARLO_CARD_SEARCHCompleted(this, new B05_SI_ARLO_CARD_SEARCHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/B05_SI_ARLO_INSERT_CARD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool B05_SI_ARLO_INSERT_CARD(System.Data.DataTable dt) {
            object[] results = this.Invoke("B05_SI_ARLO_INSERT_CARD", new object[] {
                        dt});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void B05_SI_ARLO_INSERT_CARDAsync(System.Data.DataTable dt) {
            this.B05_SI_ARLO_INSERT_CARDAsync(dt, null);
        }
        
        /// <remarks/>
        public void B05_SI_ARLO_INSERT_CARDAsync(System.Data.DataTable dt, object userState) {
            if ((this.B05_SI_ARLO_INSERT_CARDOperationCompleted == null)) {
                this.B05_SI_ARLO_INSERT_CARDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnB05_SI_ARLO_INSERT_CARDOperationCompleted);
            }
            this.InvokeAsync("B05_SI_ARLO_INSERT_CARD", new object[] {
                        dt}, this.B05_SI_ARLO_INSERT_CARDOperationCompleted, userState);
        }
        
        private void OnB05_SI_ARLO_INSERT_CARDOperationCompleted(object arg) {
            if ((this.B05_SI_ARLO_INSERT_CARDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.B05_SI_ARLO_INSERT_CARDCompleted(this, new B05_SI_ARLO_INSERT_CARDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/B05_SI_ARLO_UPDATE_CARD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool B05_SI_ARLO_UPDATE_CARD(string iCardID, string iType, int iAddTestedTimes) {
            object[] results = this.Invoke("B05_SI_ARLO_UPDATE_CARD", new object[] {
                        iCardID,
                        iType,
                        iAddTestedTimes});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void B05_SI_ARLO_UPDATE_CARDAsync(string iCardID, string iType, int iAddTestedTimes) {
            this.B05_SI_ARLO_UPDATE_CARDAsync(iCardID, iType, iAddTestedTimes, null);
        }
        
        /// <remarks/>
        public void B05_SI_ARLO_UPDATE_CARDAsync(string iCardID, string iType, int iAddTestedTimes, object userState) {
            if ((this.B05_SI_ARLO_UPDATE_CARDOperationCompleted == null)) {
                this.B05_SI_ARLO_UPDATE_CARDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnB05_SI_ARLO_UPDATE_CARDOperationCompleted);
            }
            this.InvokeAsync("B05_SI_ARLO_UPDATE_CARD", new object[] {
                        iCardID,
                        iType,
                        iAddTestedTimes}, this.B05_SI_ARLO_UPDATE_CARDOperationCompleted, userState);
        }
        
        private void OnB05_SI_ARLO_UPDATE_CARDOperationCompleted(object arg) {
            if ((this.B05_SI_ARLO_UPDATE_CARDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.B05_SI_ARLO_UPDATE_CARDCompleted(this, new B05_SI_ARLO_UPDATE_CARDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/P_B05_ARLO_UPH_SOLVED", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string P_B05_ARLO_UPH_SOLVED(string iMo, string iStation, string iModel, string iErrorCode, string iEmpId, string iAction) {
            object[] results = this.Invoke("P_B05_ARLO_UPH_SOLVED", new object[] {
                        iMo,
                        iStation,
                        iModel,
                        iErrorCode,
                        iEmpId,
                        iAction});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void P_B05_ARLO_UPH_SOLVEDAsync(string iMo, string iStation, string iModel, string iErrorCode, string iEmpId, string iAction) {
            this.P_B05_ARLO_UPH_SOLVEDAsync(iMo, iStation, iModel, iErrorCode, iEmpId, iAction, null);
        }
        
        /// <remarks/>
        public void P_B05_ARLO_UPH_SOLVEDAsync(string iMo, string iStation, string iModel, string iErrorCode, string iEmpId, string iAction, object userState) {
            if ((this.P_B05_ARLO_UPH_SOLVEDOperationCompleted == null)) {
                this.P_B05_ARLO_UPH_SOLVEDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnP_B05_ARLO_UPH_SOLVEDOperationCompleted);
            }
            this.InvokeAsync("P_B05_ARLO_UPH_SOLVED", new object[] {
                        iMo,
                        iStation,
                        iModel,
                        iErrorCode,
                        iEmpId,
                        iAction}, this.P_B05_ARLO_UPH_SOLVEDOperationCompleted, userState);
        }
        
        private void OnP_B05_ARLO_UPH_SOLVEDOperationCompleted(object arg) {
            if ((this.P_B05_ARLO_UPH_SOLVEDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.P_B05_ARLO_UPH_SOLVEDCompleted(this, new P_B05_ARLO_UPH_SOLVEDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/P_B05_ARLO_UPH_CONTROL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool P_B05_ARLO_UPH_CONTROL(string iMo, string iR_DUT, string iStation, string iModel, string iAte_name, string iAte_ip, string iYrate) {
            object[] results = this.Invoke("P_B05_ARLO_UPH_CONTROL", new object[] {
                        iMo,
                        iR_DUT,
                        iStation,
                        iModel,
                        iAte_name,
                        iAte_ip,
                        iYrate});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void P_B05_ARLO_UPH_CONTROLAsync(string iMo, string iR_DUT, string iStation, string iModel, string iAte_name, string iAte_ip, string iYrate) {
            this.P_B05_ARLO_UPH_CONTROLAsync(iMo, iR_DUT, iStation, iModel, iAte_name, iAte_ip, iYrate, null);
        }
        
        /// <remarks/>
        public void P_B05_ARLO_UPH_CONTROLAsync(string iMo, string iR_DUT, string iStation, string iModel, string iAte_name, string iAte_ip, string iYrate, object userState) {
            if ((this.P_B05_ARLO_UPH_CONTROLOperationCompleted == null)) {
                this.P_B05_ARLO_UPH_CONTROLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnP_B05_ARLO_UPH_CONTROLOperationCompleted);
            }
            this.InvokeAsync("P_B05_ARLO_UPH_CONTROL", new object[] {
                        iMo,
                        iR_DUT,
                        iStation,
                        iModel,
                        iAte_name,
                        iAte_ip,
                        iYrate}, this.P_B05_ARLO_UPH_CONTROLOperationCompleted, userState);
        }
        
        private void OnP_B05_ARLO_UPH_CONTROLOperationCompleted(object arg) {
            if ((this.P_B05_ARLO_UPH_CONTROLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.P_B05_ARLO_UPH_CONTROLCompleted(this, new P_B05_ARLO_UPH_CONTROLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/P_B05_QA_LCR_SEARCH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet P_B05_QA_LCR_SEARCH(string from, string to) {
            object[] results = this.Invoke("P_B05_QA_LCR_SEARCH", new object[] {
                        from,
                        to});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void P_B05_QA_LCR_SEARCHAsync(string from, string to) {
            this.P_B05_QA_LCR_SEARCHAsync(from, to, null);
        }
        
        /// <remarks/>
        public void P_B05_QA_LCR_SEARCHAsync(string from, string to, object userState) {
            if ((this.P_B05_QA_LCR_SEARCHOperationCompleted == null)) {
                this.P_B05_QA_LCR_SEARCHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnP_B05_QA_LCR_SEARCHOperationCompleted);
            }
            this.InvokeAsync("P_B05_QA_LCR_SEARCH", new object[] {
                        from,
                        to}, this.P_B05_QA_LCR_SEARCHOperationCompleted, userState);
        }
        
        private void OnP_B05_QA_LCR_SEARCHOperationCompleted(object arg) {
            if ((this.P_B05_QA_LCR_SEARCHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.P_B05_QA_LCR_SEARCHCompleted(this, new P_B05_QA_LCR_SEARCHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/P_B05_QA_LCR_DATA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string P_B05_QA_LCR_DATA(string SHIFT, string SN, string PN_NO, string QTY, string NAME, string ACTUALVAL, string SPEC, string DOC_NO, string REMARK, string STATUS) {
            object[] results = this.Invoke("P_B05_QA_LCR_DATA", new object[] {
                        SHIFT,
                        SN,
                        PN_NO,
                        QTY,
                        NAME,
                        ACTUALVAL,
                        SPEC,
                        DOC_NO,
                        REMARK,
                        STATUS});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void P_B05_QA_LCR_DATAAsync(string SHIFT, string SN, string PN_NO, string QTY, string NAME, string ACTUALVAL, string SPEC, string DOC_NO, string REMARK, string STATUS) {
            this.P_B05_QA_LCR_DATAAsync(SHIFT, SN, PN_NO, QTY, NAME, ACTUALVAL, SPEC, DOC_NO, REMARK, STATUS, null);
        }
        
        /// <remarks/>
        public void P_B05_QA_LCR_DATAAsync(string SHIFT, string SN, string PN_NO, string QTY, string NAME, string ACTUALVAL, string SPEC, string DOC_NO, string REMARK, string STATUS, object userState) {
            if ((this.P_B05_QA_LCR_DATAOperationCompleted == null)) {
                this.P_B05_QA_LCR_DATAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnP_B05_QA_LCR_DATAOperationCompleted);
            }
            this.InvokeAsync("P_B05_QA_LCR_DATA", new object[] {
                        SHIFT,
                        SN,
                        PN_NO,
                        QTY,
                        NAME,
                        ACTUALVAL,
                        SPEC,
                        DOC_NO,
                        REMARK,
                        STATUS}, this.P_B05_QA_LCR_DATAOperationCompleted, userState);
        }
        
        private void OnP_B05_QA_LCR_DATAOperationCompleted(object arg) {
            if ((this.P_B05_QA_LCR_DATACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.P_B05_QA_LCR_DATACompleted(this, new P_B05_QA_LCR_DATACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/P_B05_TE_CHECK_USERS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool P_B05_TE_CHECK_USERS(string user, string pw) {
            object[] results = this.Invoke("P_B05_TE_CHECK_USERS", new object[] {
                        user,
                        pw});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void P_B05_TE_CHECK_USERSAsync(string user, string pw) {
            this.P_B05_TE_CHECK_USERSAsync(user, pw, null);
        }
        
        /// <remarks/>
        public void P_B05_TE_CHECK_USERSAsync(string user, string pw, object userState) {
            if ((this.P_B05_TE_CHECK_USERSOperationCompleted == null)) {
                this.P_B05_TE_CHECK_USERSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnP_B05_TE_CHECK_USERSOperationCompleted);
            }
            this.InvokeAsync("P_B05_TE_CHECK_USERS", new object[] {
                        user,
                        pw}, this.P_B05_TE_CHECK_USERSOperationCompleted, userState);
        }
        
        private void OnP_B05_TE_CHECK_USERSOperationCompleted(object arg) {
            if ((this.P_B05_TE_CHECK_USERSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.P_B05_TE_CHECK_USERSCompleted(this, new P_B05_TE_CHECK_USERSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/P_B05_MEASURE_LUX_CONTROL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool P_B05_MEASURE_LUX_CONTROL(string model_name, string station, string box_serial, string strMeasureValue, string strtypeValue, string test_date, string strTarget_TCP, string strSlotName, string strRunTime) {
            object[] results = this.Invoke("P_B05_MEASURE_LUX_CONTROL", new object[] {
                        model_name,
                        station,
                        box_serial,
                        strMeasureValue,
                        strtypeValue,
                        test_date,
                        strTarget_TCP,
                        strSlotName,
                        strRunTime});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void P_B05_MEASURE_LUX_CONTROLAsync(string model_name, string station, string box_serial, string strMeasureValue, string strtypeValue, string test_date, string strTarget_TCP, string strSlotName, string strRunTime) {
            this.P_B05_MEASURE_LUX_CONTROLAsync(model_name, station, box_serial, strMeasureValue, strtypeValue, test_date, strTarget_TCP, strSlotName, strRunTime, null);
        }
        
        /// <remarks/>
        public void P_B05_MEASURE_LUX_CONTROLAsync(string model_name, string station, string box_serial, string strMeasureValue, string strtypeValue, string test_date, string strTarget_TCP, string strSlotName, string strRunTime, object userState) {
            if ((this.P_B05_MEASURE_LUX_CONTROLOperationCompleted == null)) {
                this.P_B05_MEASURE_LUX_CONTROLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnP_B05_MEASURE_LUX_CONTROLOperationCompleted);
            }
            this.InvokeAsync("P_B05_MEASURE_LUX_CONTROL", new object[] {
                        model_name,
                        station,
                        box_serial,
                        strMeasureValue,
                        strtypeValue,
                        test_date,
                        strTarget_TCP,
                        strSlotName,
                        strRunTime}, this.P_B05_MEASURE_LUX_CONTROLOperationCompleted, userState);
        }
        
        private void OnP_B05_MEASURE_LUX_CONTROLOperationCompleted(object arg) {
            if ((this.P_B05_MEASURE_LUX_CONTROLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.P_B05_MEASURE_LUX_CONTROLCompleted(this, new P_B05_MEASURE_LUX_CONTROLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/P_B05_MEASURE_LUX_DT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string P_B05_MEASURE_LUX_DT(System.Data.DataTable dt) {
            object[] results = this.Invoke("P_B05_MEASURE_LUX_DT", new object[] {
                        dt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void P_B05_MEASURE_LUX_DTAsync(System.Data.DataTable dt) {
            this.P_B05_MEASURE_LUX_DTAsync(dt, null);
        }
        
        /// <remarks/>
        public void P_B05_MEASURE_LUX_DTAsync(System.Data.DataTable dt, object userState) {
            if ((this.P_B05_MEASURE_LUX_DTOperationCompleted == null)) {
                this.P_B05_MEASURE_LUX_DTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnP_B05_MEASURE_LUX_DTOperationCompleted);
            }
            this.InvokeAsync("P_B05_MEASURE_LUX_DT", new object[] {
                        dt}, this.P_B05_MEASURE_LUX_DTOperationCompleted, userState);
        }
        
        private void OnP_B05_MEASURE_LUX_DTOperationCompleted(object arg) {
            if ((this.P_B05_MEASURE_LUX_DTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.P_B05_MEASURE_LUX_DTCompleted(this, new P_B05_MEASURE_LUX_DTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/P_B05_MEASURE_LUX_DTNEW", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string P_B05_MEASURE_LUX_DTNEW(System.Data.DataTable dt) {
            object[] results = this.Invoke("P_B05_MEASURE_LUX_DTNEW", new object[] {
                        dt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void P_B05_MEASURE_LUX_DTNEWAsync(System.Data.DataTable dt) {
            this.P_B05_MEASURE_LUX_DTNEWAsync(dt, null);
        }
        
        /// <remarks/>
        public void P_B05_MEASURE_LUX_DTNEWAsync(System.Data.DataTable dt, object userState) {
            if ((this.P_B05_MEASURE_LUX_DTNEWOperationCompleted == null)) {
                this.P_B05_MEASURE_LUX_DTNEWOperationCompleted = new System.Threading.SendOrPostCallback(this.OnP_B05_MEASURE_LUX_DTNEWOperationCompleted);
            }
            this.InvokeAsync("P_B05_MEASURE_LUX_DTNEW", new object[] {
                        dt}, this.P_B05_MEASURE_LUX_DTNEWOperationCompleted, userState);
        }
        
        private void OnP_B05_MEASURE_LUX_DTNEWOperationCompleted(object arg) {
            if ((this.P_B05_MEASURE_LUX_DTNEWCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.P_B05_MEASURE_LUX_DTNEWCompleted(this, new P_B05_MEASURE_LUX_DTNEWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/P_B05_ITEMNAME_CONFIG", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string P_B05_ITEMNAME_CONFIG(string product_name, string model_name, string station_name, string[] item_name, string[] item_id, string[] lsl, string[] usl) {
            object[] results = this.Invoke("P_B05_ITEMNAME_CONFIG", new object[] {
                        product_name,
                        model_name,
                        station_name,
                        item_name,
                        item_id,
                        lsl,
                        usl});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void P_B05_ITEMNAME_CONFIGAsync(string product_name, string model_name, string station_name, string[] item_name, string[] item_id, string[] lsl, string[] usl) {
            this.P_B05_ITEMNAME_CONFIGAsync(product_name, model_name, station_name, item_name, item_id, lsl, usl, null);
        }
        
        /// <remarks/>
        public void P_B05_ITEMNAME_CONFIGAsync(string product_name, string model_name, string station_name, string[] item_name, string[] item_id, string[] lsl, string[] usl, object userState) {
            if ((this.P_B05_ITEMNAME_CONFIGOperationCompleted == null)) {
                this.P_B05_ITEMNAME_CONFIGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnP_B05_ITEMNAME_CONFIGOperationCompleted);
            }
            this.InvokeAsync("P_B05_ITEMNAME_CONFIG", new object[] {
                        product_name,
                        model_name,
                        station_name,
                        item_name,
                        item_id,
                        lsl,
                        usl}, this.P_B05_ITEMNAME_CONFIGOperationCompleted, userState);
        }
        
        private void OnP_B05_ITEMNAME_CONFIGOperationCompleted(object arg) {
            if ((this.P_B05_ITEMNAME_CONFIGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.P_B05_ITEMNAME_CONFIGCompleted(this, new P_B05_ITEMNAME_CONFIGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/P_B05_CHECK_GOLDEN_DATA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool P_B05_CHECK_GOLDEN_DATA(string ate_name, string model_name, string station_name, string line_name) {
            object[] results = this.Invoke("P_B05_CHECK_GOLDEN_DATA", new object[] {
                        ate_name,
                        model_name,
                        station_name,
                        line_name});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void P_B05_CHECK_GOLDEN_DATAAsync(string ate_name, string model_name, string station_name, string line_name) {
            this.P_B05_CHECK_GOLDEN_DATAAsync(ate_name, model_name, station_name, line_name, null);
        }
        
        /// <remarks/>
        public void P_B05_CHECK_GOLDEN_DATAAsync(string ate_name, string model_name, string station_name, string line_name, object userState) {
            if ((this.P_B05_CHECK_GOLDEN_DATAOperationCompleted == null)) {
                this.P_B05_CHECK_GOLDEN_DATAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnP_B05_CHECK_GOLDEN_DATAOperationCompleted);
            }
            this.InvokeAsync("P_B05_CHECK_GOLDEN_DATA", new object[] {
                        ate_name,
                        model_name,
                        station_name,
                        line_name}, this.P_B05_CHECK_GOLDEN_DATAOperationCompleted, userState);
        }
        
        private void OnP_B05_CHECK_GOLDEN_DATAOperationCompleted(object arg) {
            if ((this.P_B05_CHECK_GOLDEN_DATACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.P_B05_CHECK_GOLDEN_DATACompleted(this, new P_B05_CHECK_GOLDEN_DATACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/P_B05_ERROR_TRACKING", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet P_B05_ERROR_TRACKING(string ate_name, string model_name, string station_name) {
            object[] results = this.Invoke("P_B05_ERROR_TRACKING", new object[] {
                        ate_name,
                        model_name,
                        station_name});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void P_B05_ERROR_TRACKINGAsync(string ate_name, string model_name, string station_name) {
            this.P_B05_ERROR_TRACKINGAsync(ate_name, model_name, station_name, null);
        }
        
        /// <remarks/>
        public void P_B05_ERROR_TRACKINGAsync(string ate_name, string model_name, string station_name, object userState) {
            if ((this.P_B05_ERROR_TRACKINGOperationCompleted == null)) {
                this.P_B05_ERROR_TRACKINGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnP_B05_ERROR_TRACKINGOperationCompleted);
            }
            this.InvokeAsync("P_B05_ERROR_TRACKING", new object[] {
                        ate_name,
                        model_name,
                        station_name}, this.P_B05_ERROR_TRACKINGOperationCompleted, userState);
        }
        
        private void OnP_B05_ERROR_TRACKINGOperationCompleted(object arg) {
            if ((this.P_B05_ERROR_TRACKINGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.P_B05_ERROR_TRACKINGCompleted(this, new P_B05_ERROR_TRACKINGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/P_B05_CALIBRATION_CONTROL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool P_B05_CALIBRATION_CONTROL(string model_name, string station_name, ref string reStr) {
            object[] results = this.Invoke("P_B05_CALIBRATION_CONTROL", new object[] {
                        model_name,
                        station_name,
                        reStr});
            reStr = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void P_B05_CALIBRATION_CONTROLAsync(string model_name, string station_name, string reStr) {
            this.P_B05_CALIBRATION_CONTROLAsync(model_name, station_name, reStr, null);
        }
        
        /// <remarks/>
        public void P_B05_CALIBRATION_CONTROLAsync(string model_name, string station_name, string reStr, object userState) {
            if ((this.P_B05_CALIBRATION_CONTROLOperationCompleted == null)) {
                this.P_B05_CALIBRATION_CONTROLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnP_B05_CALIBRATION_CONTROLOperationCompleted);
            }
            this.InvokeAsync("P_B05_CALIBRATION_CONTROL", new object[] {
                        model_name,
                        station_name,
                        reStr}, this.P_B05_CALIBRATION_CONTROLOperationCompleted, userState);
        }
        
        private void OnP_B05_CALIBRATION_CONTROLOperationCompleted(object arg) {
            if ((this.P_B05_CALIBRATION_CONTROLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.P_B05_CALIBRATION_CONTROLCompleted(this, new P_B05_CALIBRATION_CONTROLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/P_B05_MYDAS_SEARCH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet P_B05_MYDAS_SEARCH() {
            object[] results = this.Invoke("P_B05_MYDAS_SEARCH", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void P_B05_MYDAS_SEARCHAsync() {
            this.P_B05_MYDAS_SEARCHAsync(null);
        }
        
        /// <remarks/>
        public void P_B05_MYDAS_SEARCHAsync(object userState) {
            if ((this.P_B05_MYDAS_SEARCHOperationCompleted == null)) {
                this.P_B05_MYDAS_SEARCHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnP_B05_MYDAS_SEARCHOperationCompleted);
            }
            this.InvokeAsync("P_B05_MYDAS_SEARCH", new object[0], this.P_B05_MYDAS_SEARCHOperationCompleted, userState);
        }
        
        private void OnP_B05_MYDAS_SEARCHOperationCompleted(object arg) {
            if ((this.P_B05_MYDAS_SEARCHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.P_B05_MYDAS_SEARCHCompleted(this, new P_B05_MYDAS_SEARCHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SHOWUI_SPECIAL_LOCK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SHOWUI_SPECIAL_LOCK(string _LOCK_KEY, string _ATE_IP, string _ATE_MAC, string _ATE_NAME, string _LOCK_STATUS, string _LOCKEMP, string _UNLOCKEMP, string _LOCK_REASON) {
            object[] results = this.Invoke("SHOWUI_SPECIAL_LOCK", new object[] {
                        _LOCK_KEY,
                        _ATE_IP,
                        _ATE_MAC,
                        _ATE_NAME,
                        _LOCK_STATUS,
                        _LOCKEMP,
                        _UNLOCKEMP,
                        _LOCK_REASON});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SHOWUI_SPECIAL_LOCKAsync(string _LOCK_KEY, string _ATE_IP, string _ATE_MAC, string _ATE_NAME, string _LOCK_STATUS, string _LOCKEMP, string _UNLOCKEMP, string _LOCK_REASON) {
            this.SHOWUI_SPECIAL_LOCKAsync(_LOCK_KEY, _ATE_IP, _ATE_MAC, _ATE_NAME, _LOCK_STATUS, _LOCKEMP, _UNLOCKEMP, _LOCK_REASON, null);
        }
        
        /// <remarks/>
        public void SHOWUI_SPECIAL_LOCKAsync(string _LOCK_KEY, string _ATE_IP, string _ATE_MAC, string _ATE_NAME, string _LOCK_STATUS, string _LOCKEMP, string _UNLOCKEMP, string _LOCK_REASON, object userState) {
            if ((this.SHOWUI_SPECIAL_LOCKOperationCompleted == null)) {
                this.SHOWUI_SPECIAL_LOCKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSHOWUI_SPECIAL_LOCKOperationCompleted);
            }
            this.InvokeAsync("SHOWUI_SPECIAL_LOCK", new object[] {
                        _LOCK_KEY,
                        _ATE_IP,
                        _ATE_MAC,
                        _ATE_NAME,
                        _LOCK_STATUS,
                        _LOCKEMP,
                        _UNLOCKEMP,
                        _LOCK_REASON}, this.SHOWUI_SPECIAL_LOCKOperationCompleted, userState);
        }
        
        private void OnSHOWUI_SPECIAL_LOCKOperationCompleted(object arg) {
            if ((this.SHOWUI_SPECIAL_LOCKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SHOWUI_SPECIAL_LOCKCompleted(this, new SHOWUI_SPECIAL_LOCKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SHOWUI_LOCK_VALIDATION", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SHOWUI_LOCK_VALIDATION(string _LOCK_KEY) {
            object[] results = this.Invoke("SHOWUI_LOCK_VALIDATION", new object[] {
                        _LOCK_KEY});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SHOWUI_LOCK_VALIDATIONAsync(string _LOCK_KEY) {
            this.SHOWUI_LOCK_VALIDATIONAsync(_LOCK_KEY, null);
        }
        
        /// <remarks/>
        public void SHOWUI_LOCK_VALIDATIONAsync(string _LOCK_KEY, object userState) {
            if ((this.SHOWUI_LOCK_VALIDATIONOperationCompleted == null)) {
                this.SHOWUI_LOCK_VALIDATIONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSHOWUI_LOCK_VALIDATIONOperationCompleted);
            }
            this.InvokeAsync("SHOWUI_LOCK_VALIDATION", new object[] {
                        _LOCK_KEY}, this.SHOWUI_LOCK_VALIDATIONOperationCompleted, userState);
        }
        
        private void OnSHOWUI_LOCK_VALIDATIONOperationCompleted(object arg) {
            if ((this.SHOWUI_LOCK_VALIDATIONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SHOWUI_LOCK_VALIDATIONCompleted(this, new SHOWUI_LOCK_VALIDATIONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AUTO_NOTICE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AUTO_NOTICE(string[] info) {
            this.Invoke("AUTO_NOTICE", new object[] {
                        info});
        }
        
        /// <remarks/>
        public void AUTO_NOTICEAsync(string[] info) {
            this.AUTO_NOTICEAsync(info, null);
        }
        
        /// <remarks/>
        public void AUTO_NOTICEAsync(string[] info, object userState) {
            if ((this.AUTO_NOTICEOperationCompleted == null)) {
                this.AUTO_NOTICEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAUTO_NOTICEOperationCompleted);
            }
            this.InvokeAsync("AUTO_NOTICE", new object[] {
                        info}, this.AUTO_NOTICEOperationCompleted, userState);
        }
        
        private void OnAUTO_NOTICEOperationCompleted(object arg) {
            if ((this.AUTO_NOTICECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AUTO_NOTICECompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SHOWUI_BACKEND_INFO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SHOWUI_BACKEND_INFO(string Line, string Station, string ModelName, string Data) {
            this.Invoke("SHOWUI_BACKEND_INFO", new object[] {
                        Line,
                        Station,
                        ModelName,
                        Data});
        }
        
        /// <remarks/>
        public void SHOWUI_BACKEND_INFOAsync(string Line, string Station, string ModelName, string Data) {
            this.SHOWUI_BACKEND_INFOAsync(Line, Station, ModelName, Data, null);
        }
        
        /// <remarks/>
        public void SHOWUI_BACKEND_INFOAsync(string Line, string Station, string ModelName, string Data, object userState) {
            if ((this.SHOWUI_BACKEND_INFOOperationCompleted == null)) {
                this.SHOWUI_BACKEND_INFOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSHOWUI_BACKEND_INFOOperationCompleted);
            }
            this.InvokeAsync("SHOWUI_BACKEND_INFO", new object[] {
                        Line,
                        Station,
                        ModelName,
                        Data}, this.SHOWUI_BACKEND_INFOOperationCompleted, userState);
        }
        
        private void OnSHOWUI_BACKEND_INFOOperationCompleted(object arg) {
            if ((this.SHOWUI_BACKEND_INFOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SHOWUI_BACKEND_INFOCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/P_B05_SMTTOP10ERRORCODE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string P_B05_SMTTOP10ERRORCODE(System.Data.DataTable dt) {
            object[] results = this.Invoke("P_B05_SMTTOP10ERRORCODE", new object[] {
                        dt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void P_B05_SMTTOP10ERRORCODEAsync(System.Data.DataTable dt) {
            this.P_B05_SMTTOP10ERRORCODEAsync(dt, null);
        }
        
        /// <remarks/>
        public void P_B05_SMTTOP10ERRORCODEAsync(System.Data.DataTable dt, object userState) {
            if ((this.P_B05_SMTTOP10ERRORCODEOperationCompleted == null)) {
                this.P_B05_SMTTOP10ERRORCODEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnP_B05_SMTTOP10ERRORCODEOperationCompleted);
            }
            this.InvokeAsync("P_B05_SMTTOP10ERRORCODE", new object[] {
                        dt}, this.P_B05_SMTTOP10ERRORCODEOperationCompleted, userState);
        }
        
        private void OnP_B05_SMTTOP10ERRORCODEOperationCompleted(object arg) {
            if ((this.P_B05_SMTTOP10ERRORCODECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.P_B05_SMTTOP10ERRORCODECompleted(this, new P_B05_SMTTOP10ERRORCODECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void checkRickSoftwareCompletedEventHandler(object sender, checkRickSoftwareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkRickSoftwareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkRickSoftwareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void checkwannacryCompletedEventHandler(object sender, checkwannacryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkwannacryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkwannacryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void B05_SI_YR_RTRATE_SEARCHCompletedEventHandler(object sender, B05_SI_YR_RTRATE_SEARCHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class B05_SI_YR_RTRATE_SEARCHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal B05_SI_YR_RTRATE_SEARCHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void P_B05_SI_YR_RTRATE_CONTROLCompletedEventHandler(object sender, P_B05_SI_YR_RTRATE_CONTROLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class P_B05_SI_YR_RTRATE_CONTROLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal P_B05_SI_YR_RTRATE_CONTROLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SHOWUI_UNLOCK_RECORDCompletedEventHandler(object sender, SHOWUI_UNLOCK_RECORDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SHOWUI_UNLOCK_RECORDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SHOWUI_UNLOCK_RECORDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void B05_SI_GETFAKE_YRCompletedEventHandler(object sender, B05_SI_GETFAKE_YRCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class B05_SI_GETFAKE_YRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal B05_SI_GETFAKE_YRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public double FAKE_YR {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public double FAKE_TRR {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void B05_SI_ARLO_CARD_SEARCHCompletedEventHandler(object sender, B05_SI_ARLO_CARD_SEARCHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class B05_SI_ARLO_CARD_SEARCHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal B05_SI_ARLO_CARD_SEARCHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void B05_SI_ARLO_INSERT_CARDCompletedEventHandler(object sender, B05_SI_ARLO_INSERT_CARDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class B05_SI_ARLO_INSERT_CARDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal B05_SI_ARLO_INSERT_CARDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void B05_SI_ARLO_UPDATE_CARDCompletedEventHandler(object sender, B05_SI_ARLO_UPDATE_CARDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class B05_SI_ARLO_UPDATE_CARDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal B05_SI_ARLO_UPDATE_CARDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void P_B05_ARLO_UPH_SOLVEDCompletedEventHandler(object sender, P_B05_ARLO_UPH_SOLVEDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class P_B05_ARLO_UPH_SOLVEDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal P_B05_ARLO_UPH_SOLVEDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void P_B05_ARLO_UPH_CONTROLCompletedEventHandler(object sender, P_B05_ARLO_UPH_CONTROLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class P_B05_ARLO_UPH_CONTROLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal P_B05_ARLO_UPH_CONTROLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void P_B05_QA_LCR_SEARCHCompletedEventHandler(object sender, P_B05_QA_LCR_SEARCHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class P_B05_QA_LCR_SEARCHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal P_B05_QA_LCR_SEARCHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void P_B05_QA_LCR_DATACompletedEventHandler(object sender, P_B05_QA_LCR_DATACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class P_B05_QA_LCR_DATACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal P_B05_QA_LCR_DATACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void P_B05_TE_CHECK_USERSCompletedEventHandler(object sender, P_B05_TE_CHECK_USERSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class P_B05_TE_CHECK_USERSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal P_B05_TE_CHECK_USERSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void P_B05_MEASURE_LUX_CONTROLCompletedEventHandler(object sender, P_B05_MEASURE_LUX_CONTROLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class P_B05_MEASURE_LUX_CONTROLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal P_B05_MEASURE_LUX_CONTROLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void P_B05_MEASURE_LUX_DTCompletedEventHandler(object sender, P_B05_MEASURE_LUX_DTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class P_B05_MEASURE_LUX_DTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal P_B05_MEASURE_LUX_DTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void P_B05_MEASURE_LUX_DTNEWCompletedEventHandler(object sender, P_B05_MEASURE_LUX_DTNEWCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class P_B05_MEASURE_LUX_DTNEWCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal P_B05_MEASURE_LUX_DTNEWCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void P_B05_ITEMNAME_CONFIGCompletedEventHandler(object sender, P_B05_ITEMNAME_CONFIGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class P_B05_ITEMNAME_CONFIGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal P_B05_ITEMNAME_CONFIGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void P_B05_CHECK_GOLDEN_DATACompletedEventHandler(object sender, P_B05_CHECK_GOLDEN_DATACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class P_B05_CHECK_GOLDEN_DATACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal P_B05_CHECK_GOLDEN_DATACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void P_B05_ERROR_TRACKINGCompletedEventHandler(object sender, P_B05_ERROR_TRACKINGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class P_B05_ERROR_TRACKINGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal P_B05_ERROR_TRACKINGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void P_B05_CALIBRATION_CONTROLCompletedEventHandler(object sender, P_B05_CALIBRATION_CONTROLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class P_B05_CALIBRATION_CONTROLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal P_B05_CALIBRATION_CONTROLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string reStr {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void P_B05_MYDAS_SEARCHCompletedEventHandler(object sender, P_B05_MYDAS_SEARCHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class P_B05_MYDAS_SEARCHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal P_B05_MYDAS_SEARCHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SHOWUI_SPECIAL_LOCKCompletedEventHandler(object sender, SHOWUI_SPECIAL_LOCKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SHOWUI_SPECIAL_LOCKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SHOWUI_SPECIAL_LOCKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SHOWUI_LOCK_VALIDATIONCompletedEventHandler(object sender, SHOWUI_LOCK_VALIDATIONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SHOWUI_LOCK_VALIDATIONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SHOWUI_LOCK_VALIDATIONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AUTO_NOTICECompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SHOWUI_BACKEND_INFOCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void P_B05_SMTTOP10ERRORCODECompletedEventHandler(object sender, P_B05_SMTTOP10ERRORCODECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class P_B05_SMTTOP10ERRORCODECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal P_B05_SMTTOP10ERRORCODECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591