//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ShowUI.SvFPS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSendMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSendMessageStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMainMessageActionStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertMainMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSystemItemIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback App_NoticeStopMachine_AddOperationCompleted;
        
        private System.Threading.SendOrPostCallback App_NoticeStopMachine_UpdateMsgActionStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback SMTReflow_AddOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateLockStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShowUI_SaveSolvedErrorOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckFixtureNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateExpiredStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTestingModelByLineOperationCompleted;
        
        private System.Threading.SendOrPostCallback ATE_INFOOperationCompleted;
        
        private System.Threading.SendOrPostCallback AutoSendEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestSendHugeDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback QA_IPQC_AUTO_EMAILOperationCompleted;
        
        private System.Threading.SendOrPostCallback QA_IPQC_UPDATE_SENDNOWOperationCompleted;
        
        private System.Threading.SendOrPostCallback QA_IPQC_GET_DEPT_EMAILOperationCompleted;
        
        private System.Threading.SendOrPostCallback QA_IPQC_GET_RES_DEPTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::ShowUI.Properties.Settings.Default.ShowUI4_6_SvFPS_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetSendMessageCompletedEventHandler GetSendMessageCompleted;
        
        /// <remarks/>
        public event UpdateSendMessageStatusCompletedEventHandler UpdateSendMessageStatusCompleted;
        
        /// <remarks/>
        public event UpdateMainMessageActionStatusCompletedEventHandler UpdateMainMessageActionStatusCompleted;
        
        /// <remarks/>
        public event InsertMainMessageCompletedEventHandler InsertMainMessageCompleted;
        
        /// <remarks/>
        public event GetSystemItemIDCompletedEventHandler GetSystemItemIDCompleted;
        
        /// <remarks/>
        public event GetUserInfoCompletedEventHandler GetUserInfoCompleted;
        
        /// <remarks/>
        public event App_NoticeStopMachine_AddCompletedEventHandler App_NoticeStopMachine_AddCompleted;
        
        /// <remarks/>
        public event App_NoticeStopMachine_UpdateMsgActionStatusCompletedEventHandler App_NoticeStopMachine_UpdateMsgActionStatusCompleted;
        
        /// <remarks/>
        public event SMTReflow_AddCompletedEventHandler SMTReflow_AddCompleted;
        
        /// <remarks/>
        public event UpdateLockStatusCompletedEventHandler UpdateLockStatusCompleted;
        
        /// <remarks/>
        public event ShowUI_SaveSolvedErrorCompletedEventHandler ShowUI_SaveSolvedErrorCompleted;
        
        /// <remarks/>
        public event CheckFixtureNoCompletedEventHandler CheckFixtureNoCompleted;
        
        /// <remarks/>
        public event UpdateExpiredStatusCompletedEventHandler UpdateExpiredStatusCompleted;
        
        /// <remarks/>
        public event GetTestingModelByLineCompletedEventHandler GetTestingModelByLineCompleted;
        
        /// <remarks/>
        public event ATE_INFOCompletedEventHandler ATE_INFOCompleted;
        
        /// <remarks/>
        public event AutoSendEmailCompletedEventHandler AutoSendEmailCompleted;
        
        /// <remarks/>
        public event TestSendHugeDataCompletedEventHandler TestSendHugeDataCompleted;
        
        /// <remarks/>
        public event QA_IPQC_AUTO_EMAILCompletedEventHandler QA_IPQC_AUTO_EMAILCompleted;
        
        /// <remarks/>
        public event QA_IPQC_UPDATE_SENDNOWCompletedEventHandler QA_IPQC_UPDATE_SENDNOWCompleted;
        
        /// <remarks/>
        public event QA_IPQC_GET_DEPT_EMAILCompletedEventHandler QA_IPQC_GET_DEPT_EMAILCompleted;
        
        /// <remarks/>
        public event QA_IPQC_GET_RES_DEPTCompletedEventHandler QA_IPQC_GET_RES_DEPTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld(string dept) {
            object[] results = this.Invoke("HelloWorld", new object[] {
                        dept});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync(string dept) {
            this.HelloWorldAsync(dept, null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(string dept, object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[] {
                        dept}, this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSendMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSendMessage(string EmployeeId) {
            object[] results = this.Invoke("GetSendMessage", new object[] {
                        EmployeeId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSendMessageAsync(string EmployeeId) {
            this.GetSendMessageAsync(EmployeeId, null);
        }
        
        /// <remarks/>
        public void GetSendMessageAsync(string EmployeeId, object userState) {
            if ((this.GetSendMessageOperationCompleted == null)) {
                this.GetSendMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSendMessageOperationCompleted);
            }
            this.InvokeAsync("GetSendMessage", new object[] {
                        EmployeeId}, this.GetSendMessageOperationCompleted, userState);
        }
        
        private void OnGetSendMessageOperationCompleted(object arg) {
            if ((this.GetSendMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSendMessageCompleted(this, new GetSendMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateSendMessageStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateSendMessageStatus(int SendMessageID, int SendMessageStatus) {
            object[] results = this.Invoke("UpdateSendMessageStatus", new object[] {
                        SendMessageID,
                        SendMessageStatus});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateSendMessageStatusAsync(int SendMessageID, int SendMessageStatus) {
            this.UpdateSendMessageStatusAsync(SendMessageID, SendMessageStatus, null);
        }
        
        /// <remarks/>
        public void UpdateSendMessageStatusAsync(int SendMessageID, int SendMessageStatus, object userState) {
            if ((this.UpdateSendMessageStatusOperationCompleted == null)) {
                this.UpdateSendMessageStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSendMessageStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateSendMessageStatus", new object[] {
                        SendMessageID,
                        SendMessageStatus}, this.UpdateSendMessageStatusOperationCompleted, userState);
        }
        
        private void OnUpdateSendMessageStatusOperationCompleted(object arg) {
            if ((this.UpdateSendMessageStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSendMessageStatusCompleted(this, new UpdateSendMessageStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateMainMessageActionStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateMainMessageActionStatus(int MainmessageID, int MainmessageActionStatus) {
            object[] results = this.Invoke("UpdateMainMessageActionStatus", new object[] {
                        MainmessageID,
                        MainmessageActionStatus});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMainMessageActionStatusAsync(int MainmessageID, int MainmessageActionStatus) {
            this.UpdateMainMessageActionStatusAsync(MainmessageID, MainmessageActionStatus, null);
        }
        
        /// <remarks/>
        public void UpdateMainMessageActionStatusAsync(int MainmessageID, int MainmessageActionStatus, object userState) {
            if ((this.UpdateMainMessageActionStatusOperationCompleted == null)) {
                this.UpdateMainMessageActionStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMainMessageActionStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateMainMessageActionStatus", new object[] {
                        MainmessageID,
                        MainmessageActionStatus}, this.UpdateMainMessageActionStatusOperationCompleted, userState);
        }
        
        private void OnUpdateMainMessageActionStatusOperationCompleted(object arg) {
            if ((this.UpdateMainMessageActionStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMainMessageActionStatusCompleted(this, new UpdateMainMessageActionStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertMainMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertMainMessage(int Item_Id, string MessageTittle, string MessageContent, string ItemDetailLink, string SendToEmployeeId, string MessageComment) {
            object[] results = this.Invoke("InsertMainMessage", new object[] {
                        Item_Id,
                        MessageTittle,
                        MessageContent,
                        ItemDetailLink,
                        SendToEmployeeId,
                        MessageComment});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertMainMessageAsync(int Item_Id, string MessageTittle, string MessageContent, string ItemDetailLink, string SendToEmployeeId, string MessageComment) {
            this.InsertMainMessageAsync(Item_Id, MessageTittle, MessageContent, ItemDetailLink, SendToEmployeeId, MessageComment, null);
        }
        
        /// <remarks/>
        public void InsertMainMessageAsync(int Item_Id, string MessageTittle, string MessageContent, string ItemDetailLink, string SendToEmployeeId, string MessageComment, object userState) {
            if ((this.InsertMainMessageOperationCompleted == null)) {
                this.InsertMainMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertMainMessageOperationCompleted);
            }
            this.InvokeAsync("InsertMainMessage", new object[] {
                        Item_Id,
                        MessageTittle,
                        MessageContent,
                        ItemDetailLink,
                        SendToEmployeeId,
                        MessageComment}, this.InsertMainMessageOperationCompleted, userState);
        }
        
        private void OnInsertMainMessageOperationCompleted(object arg) {
            if ((this.InsertMainMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertMainMessageCompleted(this, new InsertMainMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSystemItemID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSystemItemID() {
            object[] results = this.Invoke("GetSystemItemID", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSystemItemIDAsync() {
            this.GetSystemItemIDAsync(null);
        }
        
        /// <remarks/>
        public void GetSystemItemIDAsync(object userState) {
            if ((this.GetSystemItemIDOperationCompleted == null)) {
                this.GetSystemItemIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSystemItemIDOperationCompleted);
            }
            this.InvokeAsync("GetSystemItemID", new object[0], this.GetSystemItemIDOperationCompleted, userState);
        }
        
        private void OnGetSystemItemIDOperationCompleted(object arg) {
            if ((this.GetSystemItemIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSystemItemIDCompleted(this, new GetSystemItemIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserInfo() {
            object[] results = this.Invoke("GetUserInfo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserInfoAsync() {
            this.GetUserInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetUserInfoAsync(object userState) {
            if ((this.GetUserInfoOperationCompleted == null)) {
                this.GetUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInfoOperationCompleted);
            }
            this.InvokeAsync("GetUserInfo", new object[0], this.GetUserInfoOperationCompleted, userState);
        }
        
        private void OnGetUserInfoOperationCompleted(object arg) {
            if ((this.GetUserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserInfoCompleted(this, new GetUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/App_NoticeStopMachine_Add", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void App_NoticeStopMachine_Add(string Line, string Station, string ATE, string ModelName, string Error) {
            this.Invoke("App_NoticeStopMachine_Add", new object[] {
                        Line,
                        Station,
                        ATE,
                        ModelName,
                        Error});
        }
        
        /// <remarks/>
        public void App_NoticeStopMachine_AddAsync(string Line, string Station, string ATE, string ModelName, string Error) {
            this.App_NoticeStopMachine_AddAsync(Line, Station, ATE, ModelName, Error, null);
        }
        
        /// <remarks/>
        public void App_NoticeStopMachine_AddAsync(string Line, string Station, string ATE, string ModelName, string Error, object userState) {
            if ((this.App_NoticeStopMachine_AddOperationCompleted == null)) {
                this.App_NoticeStopMachine_AddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApp_NoticeStopMachine_AddOperationCompleted);
            }
            this.InvokeAsync("App_NoticeStopMachine_Add", new object[] {
                        Line,
                        Station,
                        ATE,
                        ModelName,
                        Error}, this.App_NoticeStopMachine_AddOperationCompleted, userState);
        }
        
        private void OnApp_NoticeStopMachine_AddOperationCompleted(object arg) {
            if ((this.App_NoticeStopMachine_AddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.App_NoticeStopMachine_AddCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/App_NoticeStopMachine_UpdateMsgActionStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void App_NoticeStopMachine_UpdateMsgActionStatus(string ATE) {
            this.Invoke("App_NoticeStopMachine_UpdateMsgActionStatus", new object[] {
                        ATE});
        }
        
        /// <remarks/>
        public void App_NoticeStopMachine_UpdateMsgActionStatusAsync(string ATE) {
            this.App_NoticeStopMachine_UpdateMsgActionStatusAsync(ATE, null);
        }
        
        /// <remarks/>
        public void App_NoticeStopMachine_UpdateMsgActionStatusAsync(string ATE, object userState) {
            if ((this.App_NoticeStopMachine_UpdateMsgActionStatusOperationCompleted == null)) {
                this.App_NoticeStopMachine_UpdateMsgActionStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApp_NoticeStopMachine_UpdateMsgActionStatusOperationCompleted);
            }
            this.InvokeAsync("App_NoticeStopMachine_UpdateMsgActionStatus", new object[] {
                        ATE}, this.App_NoticeStopMachine_UpdateMsgActionStatusOperationCompleted, userState);
        }
        
        private void OnApp_NoticeStopMachine_UpdateMsgActionStatusOperationCompleted(object arg) {
            if ((this.App_NoticeStopMachine_UpdateMsgActionStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.App_NoticeStopMachine_UpdateMsgActionStatusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SMTReflow_Add", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SMTReflow_Add(string Line, string ModelName, string Error) {
            this.Invoke("SMTReflow_Add", new object[] {
                        Line,
                        ModelName,
                        Error});
        }
        
        /// <remarks/>
        public void SMTReflow_AddAsync(string Line, string ModelName, string Error) {
            this.SMTReflow_AddAsync(Line, ModelName, Error, null);
        }
        
        /// <remarks/>
        public void SMTReflow_AddAsync(string Line, string ModelName, string Error, object userState) {
            if ((this.SMTReflow_AddOperationCompleted == null)) {
                this.SMTReflow_AddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSMTReflow_AddOperationCompleted);
            }
            this.InvokeAsync("SMTReflow_Add", new object[] {
                        Line,
                        ModelName,
                        Error}, this.SMTReflow_AddOperationCompleted, userState);
        }
        
        private void OnSMTReflow_AddOperationCompleted(object arg) {
            if ((this.SMTReflow_AddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SMTReflow_AddCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateLockStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateLockStatus(string STATION_NAME, string Status) {
            this.Invoke("UpdateLockStatus", new object[] {
                        STATION_NAME,
                        Status});
        }
        
        /// <remarks/>
        public void UpdateLockStatusAsync(string STATION_NAME, string Status) {
            this.UpdateLockStatusAsync(STATION_NAME, Status, null);
        }
        
        /// <remarks/>
        public void UpdateLockStatusAsync(string STATION_NAME, string Status, object userState) {
            if ((this.UpdateLockStatusOperationCompleted == null)) {
                this.UpdateLockStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateLockStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateLockStatus", new object[] {
                        STATION_NAME,
                        Status}, this.UpdateLockStatusOperationCompleted, userState);
        }
        
        private void OnUpdateLockStatusOperationCompleted(object arg) {
            if ((this.UpdateLockStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateLockStatusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ShowUI_SaveSolvedError", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ShowUI_SaveSolvedError(string ATE_NAME, string LINE, string STATION, string MODEL_NAME, string ERROR, string SOLVED_EMP, string START_TIME, string END_TIME, string ACTION) {
            this.Invoke("ShowUI_SaveSolvedError", new object[] {
                        ATE_NAME,
                        LINE,
                        STATION,
                        MODEL_NAME,
                        ERROR,
                        SOLVED_EMP,
                        START_TIME,
                        END_TIME,
                        ACTION});
        }
        
        /// <remarks/>
        public void ShowUI_SaveSolvedErrorAsync(string ATE_NAME, string LINE, string STATION, string MODEL_NAME, string ERROR, string SOLVED_EMP, string START_TIME, string END_TIME, string ACTION) {
            this.ShowUI_SaveSolvedErrorAsync(ATE_NAME, LINE, STATION, MODEL_NAME, ERROR, SOLVED_EMP, START_TIME, END_TIME, ACTION, null);
        }
        
        /// <remarks/>
        public void ShowUI_SaveSolvedErrorAsync(string ATE_NAME, string LINE, string STATION, string MODEL_NAME, string ERROR, string SOLVED_EMP, string START_TIME, string END_TIME, string ACTION, object userState) {
            if ((this.ShowUI_SaveSolvedErrorOperationCompleted == null)) {
                this.ShowUI_SaveSolvedErrorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowUI_SaveSolvedErrorOperationCompleted);
            }
            this.InvokeAsync("ShowUI_SaveSolvedError", new object[] {
                        ATE_NAME,
                        LINE,
                        STATION,
                        MODEL_NAME,
                        ERROR,
                        SOLVED_EMP,
                        START_TIME,
                        END_TIME,
                        ACTION}, this.ShowUI_SaveSolvedErrorOperationCompleted, userState);
        }
        
        private void OnShowUI_SaveSolvedErrorOperationCompleted(object arg) {
            if ((this.ShowUI_SaveSolvedErrorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShowUI_SaveSolvedErrorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckFixtureNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CheckFixtureNo(string Model, string Station) {
            object[] results = this.Invoke("CheckFixtureNo", new object[] {
                        Model,
                        Station});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CheckFixtureNoAsync(string Model, string Station) {
            this.CheckFixtureNoAsync(Model, Station, null);
        }
        
        /// <remarks/>
        public void CheckFixtureNoAsync(string Model, string Station, object userState) {
            if ((this.CheckFixtureNoOperationCompleted == null)) {
                this.CheckFixtureNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckFixtureNoOperationCompleted);
            }
            this.InvokeAsync("CheckFixtureNo", new object[] {
                        Model,
                        Station}, this.CheckFixtureNoOperationCompleted, userState);
        }
        
        private void OnCheckFixtureNoOperationCompleted(object arg) {
            if ((this.CheckFixtureNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckFixtureNoCompleted(this, new CheckFixtureNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateExpiredStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateExpiredStatus(string Model, string Station) {
            this.Invoke("UpdateExpiredStatus", new object[] {
                        Model,
                        Station});
        }
        
        /// <remarks/>
        public void UpdateExpiredStatusAsync(string Model, string Station) {
            this.UpdateExpiredStatusAsync(Model, Station, null);
        }
        
        /// <remarks/>
        public void UpdateExpiredStatusAsync(string Model, string Station, object userState) {
            if ((this.UpdateExpiredStatusOperationCompleted == null)) {
                this.UpdateExpiredStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateExpiredStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateExpiredStatus", new object[] {
                        Model,
                        Station}, this.UpdateExpiredStatusOperationCompleted, userState);
        }
        
        private void OnUpdateExpiredStatusOperationCompleted(object arg) {
            if ((this.UpdateExpiredStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateExpiredStatusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTestingModelByLine", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTestingModelByLine(string line) {
            object[] results = this.Invoke("GetTestingModelByLine", new object[] {
                        line});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTestingModelByLineAsync(string line) {
            this.GetTestingModelByLineAsync(line, null);
        }
        
        /// <remarks/>
        public void GetTestingModelByLineAsync(string line, object userState) {
            if ((this.GetTestingModelByLineOperationCompleted == null)) {
                this.GetTestingModelByLineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTestingModelByLineOperationCompleted);
            }
            this.InvokeAsync("GetTestingModelByLine", new object[] {
                        line}, this.GetTestingModelByLineOperationCompleted, userState);
        }
        
        private void OnGetTestingModelByLineOperationCompleted(object arg) {
            if ((this.GetTestingModelByLineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTestingModelByLineCompleted(this, new GetTestingModelByLineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ATE_INFO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ATE_INFO(string ATE, string IP, string MAC, string STATION, string LINE, string LOCK_STATUS, string ON_STATUS, string IDLE_STATUS, string IQSN, string ON_TIME, string OFF_TIME, string TEST_TIME, string IDLE_TIME) {
            object[] results = this.Invoke("ATE_INFO", new object[] {
                        ATE,
                        IP,
                        MAC,
                        STATION,
                        LINE,
                        LOCK_STATUS,
                        ON_STATUS,
                        IDLE_STATUS,
                        IQSN,
                        ON_TIME,
                        OFF_TIME,
                        TEST_TIME,
                        IDLE_TIME});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ATE_INFOAsync(string ATE, string IP, string MAC, string STATION, string LINE, string LOCK_STATUS, string ON_STATUS, string IDLE_STATUS, string IQSN, string ON_TIME, string OFF_TIME, string TEST_TIME, string IDLE_TIME) {
            this.ATE_INFOAsync(ATE, IP, MAC, STATION, LINE, LOCK_STATUS, ON_STATUS, IDLE_STATUS, IQSN, ON_TIME, OFF_TIME, TEST_TIME, IDLE_TIME, null);
        }
        
        /// <remarks/>
        public void ATE_INFOAsync(string ATE, string IP, string MAC, string STATION, string LINE, string LOCK_STATUS, string ON_STATUS, string IDLE_STATUS, string IQSN, string ON_TIME, string OFF_TIME, string TEST_TIME, string IDLE_TIME, object userState) {
            if ((this.ATE_INFOOperationCompleted == null)) {
                this.ATE_INFOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnATE_INFOOperationCompleted);
            }
            this.InvokeAsync("ATE_INFO", new object[] {
                        ATE,
                        IP,
                        MAC,
                        STATION,
                        LINE,
                        LOCK_STATUS,
                        ON_STATUS,
                        IDLE_STATUS,
                        IQSN,
                        ON_TIME,
                        OFF_TIME,
                        TEST_TIME,
                        IDLE_TIME}, this.ATE_INFOOperationCompleted, userState);
        }
        
        private void OnATE_INFOOperationCompleted(object arg) {
            if ((this.ATE_INFOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ATE_INFOCompleted(this, new ATE_INFOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AutoSendEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] AutoSendEmail() {
            object[] results = this.Invoke("AutoSendEmail", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void AutoSendEmailAsync() {
            this.AutoSendEmailAsync(null);
        }
        
        /// <remarks/>
        public void AutoSendEmailAsync(object userState) {
            if ((this.AutoSendEmailOperationCompleted == null)) {
                this.AutoSendEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutoSendEmailOperationCompleted);
            }
            this.InvokeAsync("AutoSendEmail", new object[0], this.AutoSendEmailOperationCompleted, userState);
        }
        
        private void OnAutoSendEmailOperationCompleted(object arg) {
            if ((this.AutoSendEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutoSendEmailCompleted(this, new AutoSendEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestSendHugeData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable TestSendHugeData(string start, string end) {
            object[] results = this.Invoke("TestSendHugeData", new object[] {
                        start,
                        end});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void TestSendHugeDataAsync(string start, string end) {
            this.TestSendHugeDataAsync(start, end, null);
        }
        
        /// <remarks/>
        public void TestSendHugeDataAsync(string start, string end, object userState) {
            if ((this.TestSendHugeDataOperationCompleted == null)) {
                this.TestSendHugeDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestSendHugeDataOperationCompleted);
            }
            this.InvokeAsync("TestSendHugeData", new object[] {
                        start,
                        end}, this.TestSendHugeDataOperationCompleted, userState);
        }
        
        private void OnTestSendHugeDataOperationCompleted(object arg) {
            if ((this.TestSendHugeDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestSendHugeDataCompleted(this, new TestSendHugeDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QA_IPQC_AUTO_EMAIL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable QA_IPQC_AUTO_EMAIL() {
            object[] results = this.Invoke("QA_IPQC_AUTO_EMAIL", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void QA_IPQC_AUTO_EMAILAsync() {
            this.QA_IPQC_AUTO_EMAILAsync(null);
        }
        
        /// <remarks/>
        public void QA_IPQC_AUTO_EMAILAsync(object userState) {
            if ((this.QA_IPQC_AUTO_EMAILOperationCompleted == null)) {
                this.QA_IPQC_AUTO_EMAILOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQA_IPQC_AUTO_EMAILOperationCompleted);
            }
            this.InvokeAsync("QA_IPQC_AUTO_EMAIL", new object[0], this.QA_IPQC_AUTO_EMAILOperationCompleted, userState);
        }
        
        private void OnQA_IPQC_AUTO_EMAILOperationCompleted(object arg) {
            if ((this.QA_IPQC_AUTO_EMAILCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QA_IPQC_AUTO_EMAILCompleted(this, new QA_IPQC_AUTO_EMAILCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QA_IPQC_UPDATE_SENDNOW", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int QA_IPQC_UPDATE_SENDNOW(string recordid) {
            object[] results = this.Invoke("QA_IPQC_UPDATE_SENDNOW", new object[] {
                        recordid});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void QA_IPQC_UPDATE_SENDNOWAsync(string recordid) {
            this.QA_IPQC_UPDATE_SENDNOWAsync(recordid, null);
        }
        
        /// <remarks/>
        public void QA_IPQC_UPDATE_SENDNOWAsync(string recordid, object userState) {
            if ((this.QA_IPQC_UPDATE_SENDNOWOperationCompleted == null)) {
                this.QA_IPQC_UPDATE_SENDNOWOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQA_IPQC_UPDATE_SENDNOWOperationCompleted);
            }
            this.InvokeAsync("QA_IPQC_UPDATE_SENDNOW", new object[] {
                        recordid}, this.QA_IPQC_UPDATE_SENDNOWOperationCompleted, userState);
        }
        
        private void OnQA_IPQC_UPDATE_SENDNOWOperationCompleted(object arg) {
            if ((this.QA_IPQC_UPDATE_SENDNOWCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QA_IPQC_UPDATE_SENDNOWCompleted(this, new QA_IPQC_UPDATE_SENDNOWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QA_IPQC_GET_DEPT_EMAIL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QA_IPQC_GET_DEPT_EMAIL(string name) {
            object[] results = this.Invoke("QA_IPQC_GET_DEPT_EMAIL", new object[] {
                        name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QA_IPQC_GET_DEPT_EMAILAsync(string name) {
            this.QA_IPQC_GET_DEPT_EMAILAsync(name, null);
        }
        
        /// <remarks/>
        public void QA_IPQC_GET_DEPT_EMAILAsync(string name, object userState) {
            if ((this.QA_IPQC_GET_DEPT_EMAILOperationCompleted == null)) {
                this.QA_IPQC_GET_DEPT_EMAILOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQA_IPQC_GET_DEPT_EMAILOperationCompleted);
            }
            this.InvokeAsync("QA_IPQC_GET_DEPT_EMAIL", new object[] {
                        name}, this.QA_IPQC_GET_DEPT_EMAILOperationCompleted, userState);
        }
        
        private void OnQA_IPQC_GET_DEPT_EMAILOperationCompleted(object arg) {
            if ((this.QA_IPQC_GET_DEPT_EMAILCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QA_IPQC_GET_DEPT_EMAILCompleted(this, new QA_IPQC_GET_DEPT_EMAILCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QA_IPQC_GET_RES_DEPT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QA_IPQC_GET_RES_DEPT(string site) {
            object[] results = this.Invoke("QA_IPQC_GET_RES_DEPT", new object[] {
                        site});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QA_IPQC_GET_RES_DEPTAsync(string site) {
            this.QA_IPQC_GET_RES_DEPTAsync(site, null);
        }
        
        /// <remarks/>
        public void QA_IPQC_GET_RES_DEPTAsync(string site, object userState) {
            if ((this.QA_IPQC_GET_RES_DEPTOperationCompleted == null)) {
                this.QA_IPQC_GET_RES_DEPTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQA_IPQC_GET_RES_DEPTOperationCompleted);
            }
            this.InvokeAsync("QA_IPQC_GET_RES_DEPT", new object[] {
                        site}, this.QA_IPQC_GET_RES_DEPTOperationCompleted, userState);
        }
        
        private void OnQA_IPQC_GET_RES_DEPTOperationCompleted(object arg) {
            if ((this.QA_IPQC_GET_RES_DEPTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QA_IPQC_GET_RES_DEPTCompleted(this, new QA_IPQC_GET_RES_DEPTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetSendMessageCompletedEventHandler(object sender, GetSendMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSendMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSendMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateSendMessageStatusCompletedEventHandler(object sender, UpdateSendMessageStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateSendMessageStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateSendMessageStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateMainMessageActionStatusCompletedEventHandler(object sender, UpdateMainMessageActionStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMainMessageActionStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMainMessageActionStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void InsertMainMessageCompletedEventHandler(object sender, InsertMainMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertMainMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertMainMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetSystemItemIDCompletedEventHandler(object sender, GetSystemItemIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSystemItemIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSystemItemIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetUserInfoCompletedEventHandler(object sender, GetUserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void App_NoticeStopMachine_AddCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void App_NoticeStopMachine_UpdateMsgActionStatusCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SMTReflow_AddCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateLockStatusCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ShowUI_SaveSolvedErrorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CheckFixtureNoCompletedEventHandler(object sender, CheckFixtureNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckFixtureNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckFixtureNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateExpiredStatusCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetTestingModelByLineCompletedEventHandler(object sender, GetTestingModelByLineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTestingModelByLineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTestingModelByLineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ATE_INFOCompletedEventHandler(object sender, ATE_INFOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ATE_INFOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ATE_INFOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AutoSendEmailCompletedEventHandler(object sender, AutoSendEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AutoSendEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AutoSendEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void TestSendHugeDataCompletedEventHandler(object sender, TestSendHugeDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestSendHugeDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestSendHugeDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QA_IPQC_AUTO_EMAILCompletedEventHandler(object sender, QA_IPQC_AUTO_EMAILCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QA_IPQC_AUTO_EMAILCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QA_IPQC_AUTO_EMAILCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QA_IPQC_UPDATE_SENDNOWCompletedEventHandler(object sender, QA_IPQC_UPDATE_SENDNOWCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QA_IPQC_UPDATE_SENDNOWCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QA_IPQC_UPDATE_SENDNOWCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QA_IPQC_GET_DEPT_EMAILCompletedEventHandler(object sender, QA_IPQC_GET_DEPT_EMAILCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QA_IPQC_GET_DEPT_EMAILCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QA_IPQC_GET_DEPT_EMAILCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QA_IPQC_GET_RES_DEPTCompletedEventHandler(object sender, QA_IPQC_GET_RES_DEPTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QA_IPQC_GET_RES_DEPTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QA_IPQC_GET_RES_DEPTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591