//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.224.81.63/PCKPI/Service/WebService.asmx")]
        public string ShowUI4_6_ATE_CHECKLIST_WebService {
            get {
                return ((string)(this["ShowUI4_6_ATE_CHECKLIST_WebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.224.81.64/service/Servicepostdata.asmx")]
        public string ShowUI4_6_GET_ATE_SUM_TESTED_DUT_Servicepostdata {
            get {
                return ((string)(this["ShowUI4_6_GET_ATE_SUM_TESTED_DUT_Servicepostdata"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.224.81.63/FPS/WebService.asmx")]
        public string ShowUI4_6_SvFPS_WebService {
            get {
                return ((string)(this["ShowUI4_6_SvFPS_WebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.224.81.63/Servicecenter/Services/B05_Service.asmx")]
        public string ShowUI4_8_B05_SERVICE_CENTER_B05_Service {
            get {
                return ((string)(this["ShowUI4_8_B05_SERVICE_CENTER_B05_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.224.81.64/B05/Servicepostdata.asmx")]
        public string ShowUI5_3_SFISB05_SV_Servicepostdata {
            get {
                return ((string)(this["ShowUI5_3_SFISB05_SV_Servicepostdata"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.224.81.64/webservicesql/webservicesql.asmx")]
        public string ShowUI5_3_SFISB05_SQL_SV_Service {
            get {
                return ((string)(this["ShowUI5_3_SFISB05_SQL_SV_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.228.110.45/ISCService/Servicepostdata.asmx")]
        public string ISC {
            get {
                return ((string)(this["ISC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.228.110.45/ISCService/Servicepostdata.asmx")]
        public string ShowUI_ISC_Service {
            get {
                return ((string)(this["ShowUI_ISC_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.228.110.45/ISCService/Servicepostdata.asmx")]
        public string ShowUI_ISC_Service_Servicepostdata {
            get {
                return ((string)(this["ShowUI_ISC_Service_Servicepostdata"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.224.81.99/ServiceCenter/Services/B05_Service.asmx")]
        public string ShowUI_ISCB05_Service_B05_Service {
            get {
                return ((string)(this["ShowUI_ISCB05_Service_B05_Service"]));
            }
        }
    }
}
