//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowUI.ThroughtputService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WipPCModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class WipPCModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STATION_NAMEField;
        
        private decimal WIPTOTALField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string STATION_NAME {
            get {
                return this.STATION_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.STATION_NAMEField, value) != true)) {
                    this.STATION_NAMEField = value;
                    this.RaisePropertyChanged("STATION_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal WIPTOTAL {
            get {
                return this.WIPTOTALField;
            }
            set {
                if ((this.WIPTOTALField.Equals(value) != true)) {
                    this.WIPTOTALField = value;
                    this.RaisePropertyChanged("WIPTOTAL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ThroughtputService.ThroughtputServiceSoap")]
    public interface ThroughtputServiceSoap {
        
        // CODEGEN: Generating message contract since element name ModelName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataThroughtputSampling", ReplyAction="*")]
        ShowUI.ThroughtputService.GetDataThroughtputSamplingResponse GetDataThroughtputSampling(ShowUI.ThroughtputService.GetDataThroughtputSamplingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataThroughtputSamplingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataThroughtputSampling", Namespace="http://tempuri.org/", Order=0)]
        public ShowUI.ThroughtputService.GetDataThroughtputSamplingRequestBody Body;
        
        public GetDataThroughtputSamplingRequest() {
        }
        
        public GetDataThroughtputSamplingRequest(ShowUI.ThroughtputService.GetDataThroughtputSamplingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataThroughtputSamplingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ModelName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Station;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Shift;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Date;
        
        public GetDataThroughtputSamplingRequestBody() {
        }
        
        public GetDataThroughtputSamplingRequestBody(string ModelName, string Station, string Shift, string Date) {
            this.ModelName = ModelName;
            this.Station = Station;
            this.Shift = Shift;
            this.Date = Date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataThroughtputSamplingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataThroughtputSamplingResponse", Namespace="http://tempuri.org/", Order=0)]
        public ShowUI.ThroughtputService.GetDataThroughtputSamplingResponseBody Body;
        
        public GetDataThroughtputSamplingResponse() {
        }
        
        public GetDataThroughtputSamplingResponse(ShowUI.ThroughtputService.GetDataThroughtputSamplingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataThroughtputSamplingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ShowUI.ThroughtputService.WipPCModel[] GetDataThroughtputSamplingResult;
        
        public GetDataThroughtputSamplingResponseBody() {
        }
        
        public GetDataThroughtputSamplingResponseBody(ShowUI.ThroughtputService.WipPCModel[] GetDataThroughtputSamplingResult) {
            this.GetDataThroughtputSamplingResult = GetDataThroughtputSamplingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ThroughtputServiceSoapChannel : ShowUI.ThroughtputService.ThroughtputServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ThroughtputServiceSoapClient : System.ServiceModel.ClientBase<ShowUI.ThroughtputService.ThroughtputServiceSoap>, ShowUI.ThroughtputService.ThroughtputServiceSoap {
        
        public ThroughtputServiceSoapClient() {
        }
        
        public ThroughtputServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ThroughtputServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ThroughtputServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ThroughtputServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ShowUI.ThroughtputService.GetDataThroughtputSamplingResponse ShowUI.ThroughtputService.ThroughtputServiceSoap.GetDataThroughtputSampling(ShowUI.ThroughtputService.GetDataThroughtputSamplingRequest request) {
            return base.Channel.GetDataThroughtputSampling(request);
        }
        
        public ShowUI.ThroughtputService.WipPCModel[] GetDataThroughtputSampling(string ModelName, string Station, string Shift, string Date) {
            ShowUI.ThroughtputService.GetDataThroughtputSamplingRequest inValue = new ShowUI.ThroughtputService.GetDataThroughtputSamplingRequest();
            inValue.Body = new ShowUI.ThroughtputService.GetDataThroughtputSamplingRequestBody();
            inValue.Body.ModelName = ModelName;
            inValue.Body.Station = Station;
            inValue.Body.Shift = Shift;
            inValue.Body.Date = Date;
            ShowUI.ThroughtputService.GetDataThroughtputSamplingResponse retVal = ((ShowUI.ThroughtputService.ThroughtputServiceSoap)(this)).GetDataThroughtputSampling(inValue);
            return retVal.Body.GetDataThroughtputSamplingResult;
        }
    }
}
