//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ShowUI.ThroughtputService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ThroughtputServiceSoap", Namespace="http://tempuri.org/")]
    public partial class ThroughtputService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDataThroughtputSamplingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ThroughtputService() {
            this.Url = global::ShowUI.Properties.Settings.Default.ShowUI_ThroughtputService_ThroughtputService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDataThroughtputSamplingCompletedEventHandler GetDataThroughtputSamplingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataThroughtputSampling", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WipPCModel[] GetDataThroughtputSampling(string ModelName, string Station, string Shift, string Date) {
            object[] results = this.Invoke("GetDataThroughtputSampling", new object[] {
                        ModelName,
                        Station,
                        Shift,
                        Date});
            return ((WipPCModel[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDataThroughtputSamplingAsync(string ModelName, string Station, string Shift, string Date) {
            this.GetDataThroughtputSamplingAsync(ModelName, Station, Shift, Date, null);
        }
        
        /// <remarks/>
        public void GetDataThroughtputSamplingAsync(string ModelName, string Station, string Shift, string Date, object userState) {
            if ((this.GetDataThroughtputSamplingOperationCompleted == null)) {
                this.GetDataThroughtputSamplingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataThroughtputSamplingOperationCompleted);
            }
            this.InvokeAsync("GetDataThroughtputSampling", new object[] {
                        ModelName,
                        Station,
                        Shift,
                        Date}, this.GetDataThroughtputSamplingOperationCompleted, userState);
        }
        
        private void OnGetDataThroughtputSamplingOperationCompleted(object arg) {
            if ((this.GetDataThroughtputSamplingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataThroughtputSamplingCompleted(this, new GetDataThroughtputSamplingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WipPCModel {
        
        private string sTATION_NAMEField;
        
        private decimal wIPTOTALField;
        
        /// <remarks/>
        public string STATION_NAME {
            get {
                return this.sTATION_NAMEField;
            }
            set {
                this.sTATION_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public decimal WIPTOTAL {
            get {
                return this.wIPTOTALField;
            }
            set {
                this.wIPTOTALField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetDataThroughtputSamplingCompletedEventHandler(object sender, GetDataThroughtputSamplingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataThroughtputSamplingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataThroughtputSamplingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WipPCModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WipPCModel[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591